version: '3.8'

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    tty: true
    depends_on:
      - db

volumes:
  db_data:
