version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn && yarn start:dev'
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    tty: true

volumes:
  backend_node_modules:
