version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
    tty: true

volumes:
  frontend_node_modules:
