version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_PASSWORD: postgres
