version: '3.8'

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - $DB_PORT:5432
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
    ports:
      - $WEB_PORT:80
    tty: true
    depends_on:
      - db

volumes:
  db_data:
